package io.github.mmhelloworld.idrisintellij.navigation

import com.intellij.codeInsight.completion.InsertHandler
import com.intellij.codeInsight.completion.InsertionContext
import com.intellij.codeInsight.lookup.LookupElement
import com.intellij.execution.configurations.GeneralCommandLine
import com.intellij.execution.process.CapturingProcessHandler
import com.intellij.notification.NotificationGroupManager
import com.intellij.notification.NotificationType
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.module.ModuleUtilCore
import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.openapi.progress.ProgressManager
import com.intellij.openapi.progress.Task
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.OrderEnumerator
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VirtualFile
import io.github.mmhelloworld.idrisintellij.ide.IdrisIdeService
import io.github.mmhelloworld.idrisintellij.settings.IdrisSettings
import java.io.File
import java.nio.file.Paths

/**
 * Java-FFI binding generation driven from the IDE. Catalog completion offers a class's full surface;
 * when the user accepts a member that has not yet been generated by `--jvm-ffi-import`, this
 * (re)generates the binding so the inserted reference resolves.
 *
 * Generation shells out to `idris2 --jvm-ffi-import` (a cold ~3-4s run — acceptable for this one-off
 * accept action, unlike the per-keystroke catalog which uses the warm ide-mode process). It is
 * demand-driven: the importer re-scans the now-saved source, so the just-inserted reference is picked
 * up and emitted alongside the previously-generated members.
 */
object IdrisJvmFfi {

    /** The module's resolved dependency classpath (jars/dirs, no SDK), path-separator joined; "" if none. */
    fun moduleClasspath(project: Project, file: VirtualFile): String {
        val module = ModuleUtilCore.findModuleForFile(file, project) ?: return ""
        return OrderEnumerator.orderEntries(module).recursively().withoutSdk().classes()
            .pathsList.pathList.joinToString(File.pathSeparator)
    }

    fun regenerate(project: Project, file: VirtualFile, internalClass: String) {
        val service = IdrisIdeService.getInstance(project)
        val root = service.rootFor(file)
        val classpath = moduleClasspath(project, file)
        val executable = IdrisSettings.getInstance().resolveExecutable()
        val relativePath = runCatching { root.relativize(Paths.get(file.path)).toString() }.getOrDefault(file.path)

        ProgressManager.getInstance().run(
            object : Task.Backgroundable(project, "Generating Java FFI bindings for $internalClass", true) {
                override fun run(indicator: ProgressIndicator) {
                    val params = buildList {
                        add("--no-banner"); add("--no-color"); add("--console-width"); add("0")
                        if (classpath.isNotEmpty()) {
                            add("--jvm-classpath"); add(classpath)
                        }
                        add("--jvm-ffi-import"); add(internalClass)
                        // --check generates (in preOptions) then typechecks and exits. A non-zero exit
                        // from unrelated in-progress errors is fine — the module is already written.
                        add("--check"); add(relativePath)
                    }
                    val commandLine = GeneralCommandLine(executable).withParameters(params).withWorkDirectory(root.toFile())
                    val output = try {
                        CapturingProcessHandler(commandLine).runProcess(120_000)
                    } catch (e: Exception) {
                        notify(project, "Could not run idris2: ${e.message}", NotificationType.ERROR)
                        return
                    }
                    // Generation failing (e.g. the class is not on the classpath) is the one case the
                    // module is NOT updated; the driver prints a clear marker for it.
                    if ((output.stdout + output.stderr).contains("JVM FFI import failed")) {
                        notify(
                            project,
                            "Could not generate FFI bindings for $internalClass — is it on the project classpath?",
                            NotificationType.WARNING,
                        )
                        return
                    }
                    // Surface the (re)generated modules in the VFS, then reload so the new member resolves
                    // (the ide-mode process reads the freshly-written .idr from disk on :load-file).
                    LocalFileSystem.getInstance().findFileByNioFile(root)
                        ?.let { VfsUtil.markDirtyAndRefresh(false, true, true, it) }
                    service.invalidateBuildCaches()
                    service.ensureLoaded(file)
                }
            },
        )
    }

    private fun notify(project: Project, message: String, type: NotificationType) {
        ApplicationManager.getApplication().invokeLater {
            if (project.isDisposed) return@invokeLater
            NotificationGroupManager.getInstance().getNotificationGroup("Idris")
                .createNotification("Idris FFI", message, type)
                .notify(project)
        }
    }
}

/** On accepting a not-yet-generated Java-FFI member, persist the edit and (re)generate its binding. */
class JvmFfiImportInsertHandler(private val internalClass: String) : InsertHandler<LookupElement> {
    override fun handleInsert(context: InsertionContext, item: LookupElement) {
        val project = context.project
        val virtualFile = context.file.virtualFile ?: return
        val document = context.document
        // Defer past the insertion's own write action, then persist so the demand-driven scanner
        // (which reads source from disk) sees the just-inserted reference.
        ApplicationManager.getApplication().invokeLater {
            FileDocumentManager.getInstance().saveDocument(document)
            IdrisJvmFfi.regenerate(project, virtualFile, internalClass)
        }
    }
}
